services:
  app:
    build: .
    ports:
      - "6080:80"
    env_file:
      - path: .env
        required: false
    volumes:
      - ./src:/app/src
      - /app/src/vendor
    restart: unless-stopped
    environment:
      - DEBUG=true
